swagger: "2.0"
info:
  title: HNG Person API
  description: API for CRUD operations on a "person" resource
  version: 1.0.0
host: https://drab-gold-sea-lion-sock.cyclic.app
basePath: /api
schemes:
  - https
paths:
  /:
    get:
      summary: Get all persons
      description: Retrieves all persons in the database.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: string
    post:
      summary: Create a new person
      description: Creates a new person in the database.
      parameters:
        - name: person
          in: body
          description: The person object to create.
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        201:
          description: Created
          schema:
            type: object
            properties:
              name:
                type: string
              id:
                type: string
  /{id}:
    get:
      summary: Get a person by ID
      description: Retrieves a person from the database by their ID.
      parameters:
        - name: id
          in: path
          description: ID of the person to retrieve
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              name:
                type: string
              id:
                type: string
    put:
      summary: Update a person by ID
      description: Updates a person in the database by their ID.
      parameters:
        - name: id
          in: path
          description: ID of the person to update
          required: true
          type: string
        - name: person
          in: body
          description: The updated person object
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              name:
                type: string
              id:
                type: string
    delete:
      summary: Delete a person by ID
      description: Deletes a person from the database by their ID.
      parameters:
        - name: id
          in: path
          description: ID of the person to delete
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              name:
                type: string
              id:
                type: string
